version: "3.1"

services:
  my-golang-app:
    image: golang:1.13.4-alpine
    container_name: my-golang-app
    build:
      context: app
      dockerfile: Dockerfile
    command: go run main.go
    volumes:
    # lokasi main.go-mu
      - .:/go/src/app
    working_dir: /go/src/app
    ports:
      - "9000:9001"
    environment:
      PORT: 9000