version: "3.1"

services:
  my-golang-app:
    image: golang:1.13.4-alpine
    container_name: my-golang-app
    build: .
    command: go run main.go
    volumes:
    # lokasi main.go-mu
      - .:/go/src/app
    working_dir: /go/src/app
    ports:
      - "3000:3001"
    environment:
      PORT: 3000