version: "3.1"

services:
  my-golang-app:
    image: golang:alpine
    container_name: my-golang-app
    build: .
    command: go run main.go
    volumes:
    # lokasi main.go-mu
      - .:/go/src/app
    working_dir: /go/src/app
    ports:
      - "3013:3013"
    environment:
      PORT: 3013
    networks:
      - go-net
    restart: always

  redis-golang:
    image: redis:alpine
    ports:
      - 6300:6379
    networks:
      - go-net
    expose:
      - 6379

networks:
  go-net:
    driver: bridge